image: docker:latest

services:
- docker:dind  # Use docker in docker service

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  REPO_URL: "$GRADLE_REPOSITORY_URL"
  REPO_USERNAME: "$GRADLE_REPOSITORY_USERNAME"
  REPO_PASSWORD: "$GRADLE_REPOSITORY_PASSWORD"

stages:
- build
- push

before_script:
- docker info  # Check docker is running
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

docker_build:
  stage: build
  script:
  - ./build.sh
  only:
  - tags

docker_push:
  stage: push
  script:
  - docker push "$DOCKER_IMAGE"
  only:
  - tags
